### ISSUE TITLE
Doesn't support Set

### ISSUE THREAD

**Issue by ruwanka** [keepcosmos/beanmother#25]
If target object has field of type Set, following exception is thrown

`io.beanmother.core.mapper.FixtureMappingException: Target setter of 'name-of-the-property' must be List or array.`

[this method](https://github.com/keepcosmos/beanmother/blob/master/beanmother-core/src/main/java/io/beanmother/core/mapper/FixtureConverterImpl.java#L129) only checks for arrays or lists, because of that having custom converter doesn't resolve the problem.

**Comment by keepcosmos** [comment]
Right, it should support `Set` interface.

**Comment by gtiwari333** [comment]
Hello,

I got this problem when using the latest version 0.8.0. 

It looks this fix was never released to maven central.

https://mvnrepository.com/artifact/io.beanmother/beanmother-core and https://oss.sonatype.org/content/repositories/releases/io/beanmother/ both 
shows the last release date to be July 2018.

Could you check?

Thanks,

**Comment by keepcosmos** [comment]
@gtiwari333 I just release fixed version, you can find soon,
