### ISSUE TITLE
Create a introduction single page.

### ISSUE THREAD

**Issue by keepcosmos** [keepcosmos/beanmother#7]
Add a single and static html page for introduction in `/docs` path.
The Introduction should be from README.md

for example)
* http://joel-costigliola.github.io/assertj/
* http://natty.joestelmach.com/

**Comment by bhaskarmac** [comment]
@keepcosmos I can work on this, I am taking this task.

**Comment by bhaskarmac** [comment]
Submitted a PR [#11](https://github.com/keepcosmos/beanmother/pull/11)
